"""
Prepare SFT data for LLM Verifier training.

Task 1: Evidence → Code (Code Prediction)
Task 2: Evidence + Code → Yes/No + Reasoning (Verification)
"""

import json
import random
import argparse
from collections import defaultdict
from pathlib import Path


def load_code_descriptions(path: str = "data/icd10_code_descriptions.jsonl") -> dict:
    """Load ICD-10 code descriptions from JSONL file"""
    code_desc = {}
    with open(path) as f:
        for line in f:
            item = json.loads(line)
            if 'code' in item and 'description' in item:
                code_desc[item['code']] = item['description']
    return code_desc


def format_evidence(sentences: list) -> str:
    """Format sentences into evidence text (no section info)"""
    texts = []
    for sent in sentences:
        text = sent.get('text', '').strip()
        if text:
            texts.append(text)
    return "\n\n".join(texts)


def create_task1_sample(record: dict, code_desc: dict) -> dict:
    """Create Task 1 sample: Evidence → Code"""
    code = record['code']
    description = code_desc.get(code, "Unknown")
    evidence = format_evidence(record.get('sentences', []))

    return {
        "conversations": [
            {
                "from": "human",
                "value": f"You are a medical coding specialist. Based on the following clinical evidence, predict the most appropriate ICD-10 diagnosis code.\n\nEvidence: {evidence}\n\nIMPORTANT: Output ONLY the code and description."
            },
            {
                "from": "gpt",
                "value": f"{code} - {description}"
            }
        ]
    }


def create_task2_sample(record: dict, code_desc: dict, label: str) -> dict:
    """Create Task 2 sample: Evidence + Code → Yes/No (without reasoning for now)"""
    code = record['code']
    description = code_desc.get(code, "Unknown")
    evidence = format_evidence(record.get('sentences', []))

    # Placeholder for reasoning - will be generated by GPT later
    if label == "Yes":
        think = "The evidence supports this diagnosis code."
    else:
        think = "The evidence does not support this diagnosis code."

    return {
        "conversations": [
            {
                "from": "human",
                "value": f"You are a medical coding specialist. Determine if the clinical evidence supports the ICD-10 diagnosis code.\n\nCode: {code} - {description}\n\nEvidence: {evidence}"
            },
            {
                "from": "gpt",
                "value": f"<think>{think}</think>\n<answer>{label}</answer>"
            }
        ],
        # Keep metadata for GPT reasoning generation
        "_meta": {
            "note_id": record['note_id'],
            "code": code,
            "is_gt": record.get('is_gt', False),
            "label": label
        }
    }


def main():
    parser = argparse.ArgumentParser(description="Prepare SFT data for LLM Verifier")
    parser.add_argument("--input", type=str, default="data/evidence_final.jsonl",
                        help="Input evidence file")
    parser.add_argument("--code-desc", type=str, default="data/icd10_code_descriptions.jsonl",
                        help="Code description file")
    parser.add_argument("--task1-train", type=str, default="data/sft_code_pred_train.json",
                        help="Task 1 training output")
    parser.add_argument("--task1-val", type=str, default="data/sft_code_pred_val.json",
                        help="Task 1 validation output")
    parser.add_argument("--task2-train", type=str, default="data/sft_verify_train.json",
                        help="Task 2 training output")
    parser.add_argument("--task2-val", type=str, default="data/sft_verify_val.json",
                        help="Task 2 validation output")
    parser.add_argument("--val-ratio", type=float, default=0.05,
                        help="Validation set ratio")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed")
    args = parser.parse_args()

    random.seed(args.seed)

    # Load code descriptions
    print("Loading code descriptions...")
    code_desc = load_code_descriptions(args.code_desc)
    print(f"  Loaded {len(code_desc)} code descriptions")

    # Load and separate GT and HN
    print(f"Loading data from {args.input}...")
    gt_by_code = defaultdict(list)
    hn_by_code = defaultdict(list)

    with open(args.input) as f:
        for line in f:
            record = json.loads(line)
            code = record['code']
            if record.get('is_gt', False):
                gt_by_code[code].append(record)
            else:
                hn_by_code[code].append(record)

    total_gt = sum(len(v) for v in gt_by_code.values())
    total_hn = sum(len(v) for v in hn_by_code.values())
    print(f"  GT samples: {total_gt}")
    print(f"  HN samples: {total_hn}")
    print(f"  Codes: {len(gt_by_code)}")

    # Sample GT for Task 2 (matching HN count per code)
    print("\nSampling GT for Task 2 (matching HN count per code)...")
    task2_gt = []
    task1_gt = []

    for code in sorted(gt_by_code.keys()):
        gt_list = gt_by_code[code]
        hn_count = len(hn_by_code.get(code, []))

        if hn_count == 0:
            # No HN for this code, all GT goes to Task 1
            task1_gt.extend(gt_list)
        elif hn_count >= len(gt_list):
            # More HN than GT, use all GT for Task 2
            task2_gt.extend(gt_list)
        else:
            # Sample hn_count GT samples for Task 2
            random.shuffle(gt_list)
            task2_gt.extend(gt_list[:hn_count])
            task1_gt.extend(gt_list[hn_count:])

    print(f"  Task 2 GT samples: {len(task2_gt)}")
    print(f"  Task 1 GT samples: {len(task1_gt)}")

    # Collect all HN for Task 2
    task2_hn = []
    for code in hn_by_code:
        task2_hn.extend(hn_by_code[code])
    print(f"  Task 2 HN samples: {len(task2_hn)}")

    # Create Task 1 samples
    print("\nCreating Task 1 samples...")
    task1_samples = [create_task1_sample(r, code_desc) for r in task1_gt]
    random.shuffle(task1_samples)

    # Split Task 1 train/val
    val_size = int(len(task1_samples) * args.val_ratio)
    task1_train = task1_samples[val_size:]
    task1_val = task1_samples[:val_size]
    print(f"  Task 1 train: {len(task1_train)}")
    print(f"  Task 1 val: {len(task1_val)}")

    # Create Task 2 samples
    print("\nCreating Task 2 samples...")
    task2_samples = []
    for r in task2_gt:
        task2_samples.append(create_task2_sample(r, code_desc, "Yes"))
    for r in task2_hn:
        task2_samples.append(create_task2_sample(r, code_desc, "No"))
    random.shuffle(task2_samples)

    # Split Task 2 train/val
    val_size = int(len(task2_samples) * args.val_ratio)
    task2_train = task2_samples[val_size:]
    task2_val = task2_samples[:val_size]
    print(f"  Task 2 train: {len(task2_train)}")
    print(f"  Task 2 val: {len(task2_val)}")

    # Verify no overlap between Task 1 and Task 2
    print("\nVerifying no overlap...")
    task1_keys = set()
    for r in task1_gt:
        task1_keys.add((r['note_id'], r['code']))

    task2_keys = set()
    for r in task2_gt:
        task2_keys.add((r['note_id'], r['code']))

    overlap = task1_keys & task2_keys
    if overlap:
        print(f"  WARNING: {len(overlap)} overlapping samples found!")
    else:
        print("  No overlap found. Good!")

    # Save outputs
    print("\nSaving outputs...")

    with open(args.task1_train, 'w') as f:
        json.dump(task1_train, f, indent=2)
    print(f"  Saved {args.task1_train}")

    with open(args.task1_val, 'w') as f:
        json.dump(task1_val, f, indent=2)
    print(f"  Saved {args.task1_val}")

    with open(args.task2_train, 'w') as f:
        json.dump(task2_train, f, indent=2)
    print(f"  Saved {args.task2_train}")

    with open(args.task2_val, 'w') as f:
        json.dump(task2_val, f, indent=2)
    print(f"  Saved {args.task2_val}")

    print("\nDone!")
    print(f"\nSummary:")
    print(f"  Task 1 (Code Prediction): {len(task1_train) + len(task1_val)} samples")
    print(f"  Task 2 (Verification): {len(task2_train) + len(task2_val)} samples")


if __name__ == "__main__":
    main()
